{
  "version": 1,
  "author": "Montassar Themri",
  "editor": "wokwi",
  "parts": [
    { "type": "board-esp32-devkit-c-v4", "id": "esp", "top": 48, "left": 14.44, "attrs": {} },
    {
      "type": "wokwi-led",
      "id": "led1",
      "top": 94.8,
      "left": 342.6,
      "rotate": 90,
      "attrs": { "color": "green" }
    },
    {
      "type": "wokwi-dht22",
      "id": "dht1",
      "top": -153.3,
      "left": 42.6,
      "attrs": { "temperature": "22.1", "humidity": "15.5" }
    },
    {
      "type": "wokwi-pir-motion-sensor",
      "id": "pir1",
      "top": 165.48,
      "left": -369.9,
      "rotate": 270,
      "attrs": {}
    },
    {
      "type": "wokwi-photoresistor-sensor",
      "id": "ldr1",
      "top": -102.4,
      "left": -296.8,
      "attrs": {}
    },
    {
      "type": "wokwi-relay-module",
      "id": "relay1",
      "top": 37.8,
      "left": -396.8,
      "rotate": 180,
      "attrs": {}
    },
    {
      "type": "wokwi-resistor",
      "id": "r1",
      "top": 71.15,
      "left": 172.8,
      "attrs": { "value": "220" }
    },
    { "type": "wokwi-led", "id": "led2", "top": -42, "left": 311, "attrs": { "color": "red" } },
    {
      "type": "wokwi-resistor",
      "id": "r2",
      "top": 32.75,
      "left": 201.6,
      "attrs": { "value": "220" }
    },
    {
      "type": "wokwi-relay-module",
      "id": "relay2",
      "top": 390.2,
      "left": -26,
      "rotate": 90,
      "attrs": {}
    },
    {
      "type": "wokwi-led",
      "id": "led3",
      "top": 267.6,
      "left": 352.2,
      "rotate": 90,
      "attrs": { "color": "yellow" }
    },
    {
      "type": "wokwi-resistor",
      "id": "r3",
      "top": 272.75,
      "left": 268.8,
      "attrs": { "value": "220" }
    },
    {
      "type": "wokwi-relay-module",
      "id": "relay3",
      "top": 390.2,
      "left": 156.4,
      "rotate": 90,
      "attrs": {}
    },
    {
      "type": "wokwi-led",
      "id": "led4",
      "top": 433.6,
      "left": -245.4,
      "rotate": 180,
      "attrs": { "color": "red" }
    },
    {
      "type": "wokwi-resistor",
      "id": "r4",
      "top": 360,
      "left": -250.15,
      "rotate": 90,
      "attrs": { "value": "1000" }
    }
  ],
  "connections": [
    [ "esp:TX", "$serialMonitor:RX", "", [] ],
    [ "esp:RX", "$serialMonitor:TX", "", [] ],
    [ "led1:A", "esp:2", "green", [ "v88.8", "h-227.6" ] ],
    [ "led1:C", "r1:2", "black", [ "v0" ] ],
    [ "r1:1", "esp:GND.2", "green", [ "v0" ] ],
    [ "dht1:VCC", "esp:3V3", "red", [ "v9.6", "h-38.55" ] ],
    [ "dht1:SDA", "esp:4", "green", [ "h67.3", "v230.4" ] ],
    [ "dht1:GND", "esp:GND.2", "black", [ "v48", "h28.8" ] ],
    [ "pir1:VCC", "esp:VIN", "red", [ "v0" ] ],
    [ "pir1:OUT", "esp:13", "blue", [ "v0" ] ],
    [ "pir1:GND", "esp:GND.1", "black", [ "v0" ] ],
    [ "ldr1:VCC", "esp:3V3", "red", [ "h0" ] ],
    [ "ldr1:DO", "esp:35", "gold", [ "h48", "v133.8" ] ],
    [ "ldr1:GND", "esp:GND.1", "black", [ "h76.8", "v220.4" ] ],
    [ "relay1:VCC", "esp:VIN", "red", [ "h67.2", "v144" ] ],
    [ "relay1:GND", "esp:GND.1", "black", [ "h96", "v106" ] ],
    [ "relay1:IN", "esp:26", "green", [ "h192", "v105.8" ] ],
    [ "relay1:NO", "esp:3V3", "purple", [ "h0" ] ],
    [ "relay1:COM", "led2:A", "cyan", [ "h267.6", "v-46.6", "h451.2" ] ],
    [ "led2:C", "r2:2", "red", [ "h0.4", "v19.2" ] ],
    [ "r2:1", "esp:GND.2", "red", [ "h-38.4", "v38.4" ] ],
    [ "relay2:VCC", "esp:VIN", "red", [ "v-28.8", "h-9.75" ] ],
    [ "relay2:GND", "esp:GND.3", "black", [ "h86.8", "v-220.8" ] ],
    [ "relay2:IN", "esp:27", "green", [ "h-76.6", "v-124.8" ] ],
    [ "relay2:NO", "esp:3V3", "green", [ "h-36.6", "v-392.4" ] ],
    [ "relay2:COM", "led3:A", "yellow", [ "h135.8", "v20.4", "h182.4" ] ],
    [ "led3:C", "r3:2", "black", [ "h0" ] ],
    [ "r3:1", "esp:GND.3", "#8f4814", [ "v0" ] ],
    [ "relay2:VCC", "esp:5V", "purple", [ "v-28.8", "h-28.95" ] ],
    [ "relay1:VCC", "esp:5V", "red", [ "h48", "v172.8" ] ],
    [ "pir1:VCC", "esp:5V", "red", [ "h9.6", "v28.8" ] ],
    [ "relay3:IN", "esp:15", "green", [ "v0" ] ],
    [ "relay3:GND", "esp:GND.3", "black", [ "v0" ] ],
    [ "relay3:VCC", "esp:5V", "limegreen", [ "v-67.2", "h-211.35" ] ],
    [ "led4:C", "r4:2", "green", [ "v0" ] ],
    [ "r4:1", "esp:GND.1", "green", [ "h134.4", "v-134.4" ] ],
    [ "relay3:COM", "led4:A", "purple", [ "v58.8", "h-469", "v-86.4" ] ],
    [ "relay3:NO", "esp:3V3", "orange", [ "v-478.8", "h-190.35" ] ]
  ],
  "dependencies": {}
}